# Generated by Django 5.0.6 on 2025-02-28 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_game_gameimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensagem de Contato', 'verbose_name_plural': 'Mensagens de Contato'},
        ),
        migrations.AddField(
            model_name='reports',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de envio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AddField(
            model_name='reports',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lida'),
        ),
    ]
