# Generated by Django 5.0.6 on 2025-02-28 18:31

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_reports_options_reports_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Data de envio'),
        ),
    ]
