# Generated by Django 5.0.6 on 2025-02-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_reports_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Jogar'),
        ),
    ]
